enum_discrim_align_threshold = 20
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
doc_comment_code_block_width = 88
format_strings = true
imports_layout = "HorizontalVertical"
