max_width = 88
doc_comment_code_block_width = 88
enum_discrim_align_threshold = 20
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
