[package]
name = "macroquest-build-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[build-dependencies]
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
