[package]
name = "mqrustskeleton"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
macroquest = { path = "../../macroquest" }

[build-dependencies]
macroquest-build-config = { path = "../../macroquest-build-config" }
