[package]
name = "macroquest"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquest-macros = { path = "../macroquest-macros" }
num_enum = "0.7.2"
parking_lot = "0.12.1"
windows = { version = "0.*", features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
] }


[build-dependencies]
macroquest-build-config = { path = "../macroquest-build-config" }
