[package]
name = "macroquest"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquest-macros = { path = "../macroquest-macros" }
cansi = { version = "2.2.1", optional = true }
cxx = "1"
num_enum = "0.7.2"
parking_lot = "0.12.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", optional = true }
windows = { version = "0.*", features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
] }


[build-dependencies]
macroquest-build-config = { path = "../macroquest-build-config" }
cxx-build = "1"
walkdir = "2"

[features]
colors = ["dep:cansi"]
logger = ["dep:tracing-subscriber"]
