name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 1 * * *"

env:
  RUSTFLAGS: -Dwarnings

jobs:
  macroquest:
    name: Build MacroQuest
    runs-on: windows-latest
    strategy:
      fail-fast: false
    outputs:
      commit: ${{ steps.build-macroquest.outputs.commit }}
    steps:
      - name: Checkout macroquest-rs
        uses: actions/checkout@v4
        with:
          path: ./crates
      - name: Build MacroQuest
        id: build-macroquest
        uses: ./crates/.github/actions/macroquest
        with:
          ref: rel-live

  clippy:
    name: Clippy
    runs-on: windows-latest
    needs: [macroquest]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout macroquest-rs
        uses: actions/checkout@v4
        with:
          path: ./crates
      - name: Build MacroQuest
        uses: ./crates/.github/actions/macroquest
        with:
          ref: ${{ needs.macroquest.outputs.commit }}
      - name: Install Clippy
        uses: dtolnay/rust-toolchain@clippy
        with:
          toolchain: nightly
      - name: Cache Rust Dependencies
        if: ${{ matrix.rust != 'nightly' }}
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates
      - name: Cache macroquest-rs
        uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo clippy --workspace --all-targets --all-features
        working-directory: ${{ github.workspace }}/crates
        env:
          MACROQUEST_DIR: ${{ github.workspace }}/MacroQuest/
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

  build:
    name: Rust ${{matrix.rust}}
    runs-on: windows-latest
    needs: [macroquest]
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - name: Checkout macroquest-rs
        uses: actions/checkout@v4
        with:
          path: ./crates
      - name: Build MacroQuest
        uses: ./crates/.github/actions/macroquest
        with:
          ref: ${{ needs.macroquest.outputs.commit }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - name: Cache Rust Dependencies
        if: ${{ matrix.rust != 'nightly' }}
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates
      - name: Cache macroquest-rs
        uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo build --workspace --all-targets
        working-directory:  ${{ github.workspace }}/crates
        env:
          MACROQUEST_DIR: ${{ github.workspace }}//MacroQuest/
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
      - run: cargo build --workspace --all-targets --all-features
        working-directory: ${{ github.workspace }}/crates
        env:
          MACROQUEST_DIR: ${{ github.workspace }}/MacroQuest/
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"


  doc:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs -p macroquest-build-config
      - run: cargo docs-rs -p macroquest-macros
      - run: cargo docs-rs -p macroquest
