name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@clippy
        with:
          toolchain: nightly
      - run: cargo clippy --workspace --all-targets --all-features


  doc:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs -p macroquest-build-config
      - run: cargo docs-rs -p macroquest-macros
      - run: cargo docs-rs -p macroquest
