name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-mingw@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-gnu
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs -p macroquest-build-config
      - run: cargo docs-rs -p macroquest-macros
      - run: cargo docs-rs -p macroquest
