name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    name: Rust ${{matrix.rust}}
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - name: Checkout macroquest-rs
        uses: actions/checkout@v4
        with:
          path: ./crates
      - name: Build MacroQuest
        uses: ./crates/.github/actions/macroquest
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build --workspace --all-targets
        working-directory: ./crates
        env:
          MACROQUEST_DIR: ../MacroQuest/
      - run: cargo build --workspace --all-targets --all-features
        working-directory: ./crates
        env:
          MACROQUEST_DIR: ../MacroQuest/

  clippy:
    name: Clippy
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout macroquest-rs
        uses: actions/checkout@v4
        with:
          path: ./crates
      - name: Build MacroQuest
        uses: ./crates/.github/actions/macroquest
      - name: Install Clippy
        uses: dtolnay/rust-toolchain@clippy
        with:
          toolchain: nightly
      - run: cargo clippy --workspace --all-targets --all-features
        working-directory: ${{ github.workspace }}/crates
        env:
          MACROQUEST_DIR: ${{ github.workspace }}/MacroQuest/


  doc:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs -p macroquest-build-config
      - run: cargo docs-rs -p macroquest-macros
      - run: cargo docs-rs -p macroquest
